1、重新设计 getTorbrowser ，增加了选择菜单。 现在可以根据需要选择：是下载 torbrowser 还是下载 tor expert bundle。 还可以选择：下载站点、支持平台。 另外，各层菜单都有设计了回退上层菜单和退出菜单的选项。
2、对 tor、mtor、privoxy、haproxy、updater 做了代码规范、优化处理。

3、tor、mtor、privoxy、haproxy 可以根据需要单独或组合启动，方便配合其他应用程序使用onion网络。

4、由于目前使用MacBook Pro，以上更新的是macOS和Linux平台代码，windows的代码待虚拟机好了再更新。

diff --git a/Linux/getTorbrowser b/Linux/getTorbrowser
--- a/Linux/getTorbrowser
+++ b/Linux/getTorbrowser
@@ -4,7 +4,7 @@
 #
 # Purpose     :  A latest version of Tor Browser/Tor Expert Bundle download script
 #
-# Copyright   :  Written by and Copyright (C) 2023-04-03
+# Copyright   :  Written by and Copyright (C) 2023-04-26
 #                Miles Guo. komg@hotmail.com
 #
 #                This program is free software; you can redistribute it
@@ -35,46 +35,298 @@ cd "$(dirname "$0")"
 # check wget
 WGETPATH=/usr/local/bin
 WGETBIN=$WGETPATH/wget
-if [ ! -x $WGETBIN ]; then
+[[ ! -x $WGETBIN ]] && {
   echo "Sorry, I can't find wget, that is used to download the Torbrowser."
   echo "Please refer to the readme.md for the solution."
+  echo
   exit 1
-fi
+}
+
+# By default, Tor & Privoxy are not started.
+TORPRIVOXY=off
+
+start_torprivoxy () {
+  [[ "$TORPRIVOXY" == "on" ]] && return 0
+  echo "We need to start Tor & Privoxy."
+  echo
+  ./tor start 2>/dev/null
+  [[ $? -ne 0 ]] && {
+    echo “An error occurred, tor did not start normally. Please resolve the issue and try again.”
+    echo
+    exit 1
+  }
+  echo
+  ./privoxy start 2>/dev/null
+  [[ $? -ne 0 ]] && {
+    echo “An error occurred, privoxy did not start normally. Please resolve the issue and try again.”
+    echo
+    exit 1
+  }
+  echo
+  TORPRIVOXY=on
+  return 0
+}
+
+stop_torprivoxy () {
+  [[ "$TORPRIVOXY" == "off" ]] && return 0
+  echo "We need to stop Tor & Privoxy."
+  echo
+  ./tor stop 2>/dev/null
+  [[ $? -ne 0 ]] && {
+    echo "An error occurred, tor did not stop normally. Please try to manually close it."
+    echo
+  }
+  echo
+  ./privoxy stop 2>/dev/null
+  [[ $? -ne 0 ]] && {
+    echo "An error occurred, privoxy did not stop normally. Please try to manually close it."
+    echo
+  }
+  echo
+  TORPRIVOXY=off
+  return 0
+}
 
 #
-# Select to download Torbrowser or Tor Expert Bundle
+# Choose what you want to download.
 #
-quitmenu="false"
-until [ "$quitmenu" == "true" ];
+menu_item1=("Torbrowser" "Tor Expert Bundle")
+menu_title1="Choose what you want to download"
+menu_quit1="false"
+PS3_num1=`expr ${#menu_item1[@]} + 1`
+until [[ "$menu_quit1" == "true" ]];
 do
-  echo "First, please select whether you want to download Torbrowser or Tor Expert Bundle"
+  echo $menu_title1
   echo
-  PS3="Make your choice [1..3]: "
-  select fav in "Torbrowser" "Tor Expert Bundle" "Quit"; do
-    case $fav in
-	    "Torbrowser")
+  PS3="Make your choice [1..$PS3_num1]: "
+  select input1 in "${menu_item1[@]}" "Quit"; do
+	  [[ "${menu_item1[@]}" =~ "${input1}" ]] && {
+      echo
+	    echo "Okay, Your choice is $input1."
+      echo
+      [[ "$input1" == "Torbrowser" ]] && tb_or_teb="tb" || tb_or_teb="teb"
+
+      #
+      # Choose the download site.
+      #
+      # Save the original default delimiter of the system
+      IFS_OLD="${IFS}"
+      # Set new delimiter
+      IFS=$'\r\n'
+      num=0
+      for site in `cat sites.txt`
+      do
+        [[ "$site" == "#"* ]] && {
+          echo -e "\c"
+        } || {
+          menu_item2[$num]=${site}
+          num=`expr $num + 1`
+        }
+      done
+      # Restore the original default delimiter of the system
+      IFS=${IFS_OLD}
+      menu_title2="Choose the download site."
+      menu_quit2="false"
+      PS3_num2=`expr ${#menu_item2[@]} + 2`
+      until [[ "$menu_quit2" == "true" ]];
+      do
+        echo $menu_title2
         echo
-	      echo "Okay, you chose to download $fav."
-        echo
-        tborteb="tb"
-        tbortebTITLE="Torbrowser"
-        quitmenu="true"
-        break
-	      ;;
-	    "Tor Expert Bundle")
-        echo
-	      echo "Okay, you chose to download $fav."
-        echo
-        tborteb="teb"
-        tbortebTITLE="Tor Expert Bundle"
-        quitmenu="true"
-        break
-	      ;;
+        PS3="Make your choice [1..$PS3_num2]: "
+        select input2 in "${menu_item2[@]}" "Previous Menu" "Quit"; do
+          [[ "${menu_item2[@]}" =~ "${input2}" ]] && {
+            echo
+            echo "Okay, Your choice is $input2."
+            echo
+            [[ "$tb_or_teb" == "tb" ]] && DL_URL=${input2}/download/ || DL_URL=${input2}/download/tor/
+            DIST_URL=${input2}/dist/torbrowser/
+            # Test $DL_URL
+            echo "Let's try whether $DL_URL can connect..."
+            echo
+            echo "$WGETBIN -q -t 1 --spider --no-check-certificate $DL_URL"
+            $WGETBIN -q -t 1 --spider --no-check-certificate $DL_URL
+            [[ $? -eq 0 ]] && {
+              echo
+              echo "Yes, the $DL_URL can be connected."
+              echo
+            } || {
+              echo
+              echo "No, the $DL_URL can't connect."
+              echo
+              start_torprivoxy
+              WGETBIN=$WGETBIN" -e https_proxy=127.0.0.1:8118"
+              # Test proxy
+              echo "Test $DL_URL again until it can be connected..."
+              echo
+              proxy_ok="false"
+              until [[ "$proxy_ok" == "true" ]];
+              do
+                echo "$WGETBIN -q -t 1 --spider --no-check-certificate $DL_URL" 
+                $WGETBIN -q -t 1 --spider --no-check-certificate $DL_URL
+                [[ $? -eq 0 ]] && proxy_ok="true" || proxy_ok="false"
+              done
+              echo "Okey, now the $DL_URL can be connected." 
+              echo
+            }
+            echo "Let's Go."
+            echo
+
+            #
+            # Set save folder for downloaded files
+            #
+            DLDIR=$HOME/Downloads/Torbrowser
+            [[ ! -d $DLDIR ]] && mkdir -p -m 700 $DLDIR >/dev/null 2>&1
+
+            #
+            # Choose the platform.
+            #
+            # Save the original default delimiter of the system
+            IFS_OLD="${IFS}"
+            # Set new delimiter
+            IFS=$'\r\n'
+            num=0
+            for platform in `cat platforms.txt`
+            do
+              [[ "$platform" == "#"* ]] && {
+                echo -e "\c"
+              } || {
+                menu_item3[$num]=$platform
+                num=`expr $num + 1`
+              }
+            done
+            # Restore the original default delimiter of the system
+            IFS=${IFS_OLD}
+            menu_title3="Choose the platform."
+            menu_quit3="false"
+            PS3_num3=`expr ${#menu_item3[@]} + 2`
+            until [[ "$menu_quit3" == "true" ]];
+            do
+              echo $menu_title3
+              echo
+              PS3="Make your choice [1..$PS3_num3]: "
+              select input3 in "${menu_item3[@]}" "Previous Menu" "Quit"; do
+                [[ "${menu_item3[@]}" =~ "${input3}" ]] && {
+                  echo
+                  echo "Okay, Your choice is $input3."
+                  echo
+                  # Get the current version number.
+                  # Save the original default delimiter of the system
+                  IFS_OLD="${IFS}"
+                  # Set new delimiter
+                  IFS=$'\r\n'
+                  i=0
+                  for str in `cat $tb_or_teb$input3.txt`
+                  do
+                    [[ "$str" == "#"* ]] && {
+                      echo -e "\c"
+                    } || {
+                      para[$i]=$str
+                      i=`expr $i + 1`
+                    }
+                  done
+                  i=`expr $i - 1`
+                  # Restore the original default delimiter of the system
+                  IFS=${IFS_OLD}
+                  echo "${para[0]}"
+                  echo "${para[1]}"
+                  echo "${para[2]}"
+                  echo
+                  echo "Get the current version number of the ${para[3]} from $DL_URL"
+                  echo
+                  str=${para[4]//PAT/([^/]+)}
+                  cutpoint=`expr $((para[5])) + 1`
+                  cutoffchars=${para[6]}
+                  $WGETBIN -q -c -O tempa.txt $DL_URL
+                  tmpstr="$(grep -o -E -m 1 "${str}" tempa.txt | cut -c ${cutpoint}-)"
+	                TBVER="${tmpstr%$cutoffchars}"
+                  echo "Current version number is: $TBVER"
+                  echo
+                  [[ -e tempa.txt ]] && rm -rf tempa.txt >/dev/null 2>&1
+                  # Download the file.
+                  echo "The downloaded files will be saved in this folder:"
+                  echo
+                  echo "  $DLDIR/$TBVER"
+                  echo
+                  for i in $(seq 7 $i)
+                  do
+                    file=${para[i]//TBVER/${TBVER}}
+                    echo "Download file $file ..."
+                    echo
+                    echo "$WGETBIN -c -t 0 -P $DLDIR/$TBVER $DIST_URL$TBVER/$file"
+                    echo
+                    $WGETBIN -c -t 0 -P $DLDIR/$TBVER $DIST_URL$TBVER/$file
+                    echo
+                  done
+                  echo "Okey, All files have been downloaded. Enjoy!"
+                  echo
+                  break
+                }
+                case $input3 in
+	                "Previous Menu")
+                    echo
+	                  echo "Okay, Your choice is to return to the previous menu."
+                    echo
+                    WGETBIN=$WGETPATH/wget
+                    menu_quit3="true"
+                    break
+	                  ;;
+	                "Quit")
+                    echo
+	                  echo "Okay, Your choice is to quit."
+                    echo
+                    stop_torprivoxy
+                    echo "Bye!"
+                    echo
+                    exit 0
+	                  ;;
+                  *)
+                    echo
+                    echo "invalid option $REPLY, try again!"
+                    echo
+                    break
+                    ;;
+                esac
+              done
+            done
+            break
+          }
+          case $input2 in
+	          "Previous Menu")
+              echo
+	            echo "Okay, Your choice is to return to the previous menu."
+              echo
+              menu_quit2="true"
+              break
+	            ;;
+	          "Quit")
+              echo
+	            echo "Okay, Your choice is to quit."
+              echo
+              stop_torprivoxy
+              echo "Bye!"
+              echo
+              exit 0
+	            ;;
+            *)
+              echo
+              echo "invalid option $REPLY, try again!"
+              echo
+              break
+              ;;
+          esac
+        done
+      done
+      break
+    }
+    case $input1 in
 	    "Quit")
         echo
-	      echo "Okay, you chose to quit. Bye!"
+	      echo "Okay, Your choice is to quit."
         echo
-        exit
+        stop_torprivoxy
+        echo "Bye!"
+        echo
+        exit 0
 	      ;;
       *)
         echo
@@ -85,250 +337,6 @@ do
     esac
   done
 done
-
-#
-# The torproject download site.
-#
-# Torbrowser's official website
-# It may be necessary to run Tor + Privoxy to connect
-# https://www.torproject.org/download/
-# https://www.torproject.org/download/tor/
-# https://dist.torproject.org/torbrowser/11.0.15/
-# https://archive.torproject.org/tor-package-archive/torbrowser/12.0.4/
-#
-# Torbrowser's mirror site
-# It seems that we can connect without running Tor + Privoxy (Recommended for use in China)
-# https://tor.calyxinstitute.org/download/
-# https://tor.calyxinstitute.org/download/tor/
-# https://tor.calyxinstitute.org/dist/torbrowser/11.0.15/
-#
-#set TEST_URL=https://aus1.torproject.org/torbrowser/update_3/release/downloads.json
-
-# Save the original default delimiter of the system
-IFS_OLD="${IFS}"
-# Set new delimiter
-IFS=$'\r\n'
-num=0
-for site in `cat sites.txt`
-do
-  [[ "$site" == "#"* ]] && {
-    echo -e "\c"
-  } || {
-    URLS[$num]=${site}
-    num=`expr $num + 1`
-  }
-done
-# Restore the original default delimiter of the system
-IFS=${IFS_OLD}
-
-#
-# Select the download site
-#
-quitmenu="false"
-options=`expr $num + 1`
-until [ "$quitmenu" == "true" ];
-do
-  echo "Now, you need to select the download site."
-  echo
-  PS3="Make your choice from the list [1..$options]: "
-  select fav in "${URLS[@]}" "Quit"; do
-    [ $REPLY -ge 1 -a $REPLY -le $num ] && {
-      echo
-      echo "Okay, the site you chose is $fav."
-      echo
-      quitmenu="true"
-      break
-    } || {
-      case $fav in
-	      "Quit")
-          echo
-	        echo "Okay, you chose to quit. Bye!"
-          echo
-          exit
-	        ;;
-        *)
-          echo
-          echo "invalid option $REPLY, try again!"
-          echo
-          break
-          ;;
-      esac
-    }
-  done
-done
-
-[ "$tborteb" == "tb" ] && {
-  DL_URL=${fav}/download/
-} || {
-  DL_URL=${fav}/download/tor/
-}
-DIST_URL=${fav}/dist/torbrowser/
-
-echo "Let's try whether $DL_URL can connect..."
-echo
-
-echo "wget -q -t 1 --spider $DL_URL"
-wget -q -t 1 --spider $DL_URL
-  
-[ $? -eq 0 ] && {
-  echo
-  echo "Yes, the $DL_URL can be connected."
-  echo
-  TORPRIVOXY=0
-} || {
-  echo
-  echo "No, the $DL_URL can't connect."
-  echo
-  TORPRIVOXY=1
-}
-
-#
-# Set save folder for downloaded files
-#
-DLDIR=$HOME/Downloads/Torbrowser
-if [ ! -d $DLDIR ]; then
-  mkdir -p -m 700 $DLDIR
-fi
-
-[ $TORPRIVOXY -eq 1 ] && {
-  echo "Since the site could not connect normally,"
-  echo "we decided to start Tor & Privoxy."
-  echo
-  ./tor start
-  ./privoxy start
-#  ./mtor 5 start
-#  ./haproxy start
-#  ./privoxy start
-}
-
-# Save the original default delimiter of the system
-IFS_OLD="${IFS}"
-# Set new delimiter
-IFS=$'\r\n'
-num=0
-for platform in `cat platforms.txt`
-do
-  [[ "$platform" == "#"* ]] && {
-    echo -e "\c"
-  } || {
-    PLATFORMS[$num]=$platform
-    num=`expr $num + 1`
-  }
-done
-# Restore the original default delimiter of the system
-IFS=${IFS_OLD}
-
-#
-# Select the platform
-#
-quitmenu="false"
-options=`expr $num + 1`
-until [ "${quitmenu}" == "true" ];
-do
-  echo "Now, you can choose the $tbortebTITLE for ..."
-  echo
-  PS3="Make your choice from the list [1..$options]: "
-  select fav in "${PLATFORMS[@]}" "Quit"; do
-    [ $REPLY -ge 1 -a $REPLY -le $num ] && {
-      echo
-      echo "Okay, the platform you chose is $fav."
-      echo
-
-      # Save the original default delimiter of the system
-      IFS_OLD="${IFS}"
-      # Set new delimiter
-      IFS=$'\r\n'
-      i=0
-      for str in `cat $tborteb$fav.txt`
-      do
-        [[ "$str" == "#"* ]] && {
-          echo -e "\c"
-        } || {
-          para[$i]=$str
-          i=`expr $i + 1`
-        }
-      done
-      i=`expr $i - 1`
-      # Restore the original default delimiter of the system
-      IFS=${IFS_OLD}
-
-      echo "${para[0]}"
-      echo "${para[1]}"
-      echo "${para[2]}"
-      echo
-      echo "Get the current version number of the ${para[3]} from $DL_URL"
-      echo
-      str=${para[4]//PAT/([^/]+)}
-      cutpoint=`expr $((para[5])) + 1`
-      cutoffchars=${para[6]}
-      [ $TORPRIVOXY -eq 0 ] && {
-        wget -q -c -O tempa.txt $DL_URL
-      } || {
-        wget -e https_proxy=127.0.0.1:8118 -q -c -O tempa.txt $DL_URL
-      }
-      tmpstr="$(grep -o -E -m 1 "${str}" tempa.txt | cut -c ${cutpoint}-)"
-	    TBVER="${tmpstr%$cutoffchars}"
-      echo "Current version number is: $TBVER"
-      echo
-      if [ -e tempa.txt ]; then
-        rm -rf tempa.txt
-      fi
-
-      echo "The downloaded files will be saved in this folder:"
-      echo
-      echo "  $DLDIR/$TBVER"
-      echo
-
-      for i in $(seq 7 $i)
-      do
-        file=${para[i]//TBVER/${TBVER}}
-        echo "Download file $file ..."
-        echo
-        [ $TORPRIVOXY -eq 0 ] && {
-          echo "wget -q -c -t 0 -P $DLDIR/$TBVER $DIST_URL$TBVER/$file"
-          wget -c -t 0 -P $DLDIR/$TBVER $DIST_URL$TBVER/$file
-        } || {
-          echo "wget -e https_proxy=127.0.0.1:8118 -q -c -t 0 -P $DLDIR/$TBVER $DIST_URL$TBVER/$file"
-          wget -e https_proxy=127.0.0.1:8118 -c -t 0 -P $DLDIR/$TBVER $DIST_URL$TBVER/$file
-        }
-        echo
-      done
-      echo "Okey, All files have been downloaded. Enjoy!"
-      echo
-      break
-    } || {
-      case $fav in
-	      "Quit")
-          echo
-	        echo "Okay, you chose to quit."
-          echo
-          quitmenu="true"
-	        break
-	        ;;
-        *)
-          echo "invalid option $REPLY, try again!"
-          echo
-          break
-          ;;
-      esac
-    }
-  done
-done
-
-[ $TORPRIVOXY -eq 0 ] && {
-  echo "Bye!"
-  echo
-} || {
-  echo "We need to kill Tor & Privoxy."
-  echo
-  ./privoxy stop
-  ./tor stop
-#  ./privoxy stop
-#  ./haproxy stop
-#  ./mtor 5 stop
-  echo "Bye!"
-  echo
-}
 
 ## End of getTorbrowser
 ######################test only######################
diff --git a/Linux/haproxy b/Linux/haproxy
--- a/Linux/haproxy
+++ b/Linux/haproxy
@@ -4,7 +4,7 @@
 #
 # Purpose     :  A fast and reliable http reverse proxy and load balancer launch/terminate/... script
 #
-# Copyright   :  Written by and Copyright (C) 2023-03-17
+# Copyright   :  Written by and Copyright (C) 2023-04-26
 #                Miles Guo. komg@hotmail.com
 #
 #                This program is free software; you can redistribute it
@@ -39,113 +39,124 @@ EOF
   exit 1
 }
 
-[ $# -ne 1 ] && usage
+[[ $# -ne 1 ]] && usage
 
 . rc.common
 
 BASENAME=`basename $0`
+
 # check haproxy
 BINPATH=/usr/local/bin
 BINFILE=$BINPATH/$BASENAME
-if [ ! -x $BINFILE ]; then
+[[ ! -x $BINFILE ]] && {
   echo "Sorry, you haven't installed $BASENAME yet."
   echo "Please refer to the readme.md for the solution."
+  echo
   exit 1
-fi
+}
 
 CFGFILE=$PWD/$BASENAME.cfg
-[ -f $CFGFILE ] || exit 1
+[[ -f $CFGFILE ]] || {
+  echo "Sorry, I can't find $CFGFILE, that is used to with $BASENAME."
+  echo
+  exit 1
+}
+
 data_dir=$PWD/run/$BASENAME
 PIDFILE=$data_dir/$BASENAME.pid
 
 RETVAL=0
 
-start() {
-  if [ -e $PIDFILE ]; then
+start () {
+  [[ -e $PIDFILE ]] && {
     echo "$BASENAME is already running."
-    return 0
-  fi
-
+    echo
+    RETVAL=0
+    return $RETVAL
+  }
   quiet_check
-  if [ $? -ne 0 ]; then
+  [[ $? -ne 0 ]] && {
     echo "Errors found in configuration file, check it with '$0 check'."
-    return 1
-  fi
-
-  if [ ! -d "$data_dir" ]; then
-    echo "Creating directory $data_dir"
-    mkdir -p -m 700 "$data_dir"
-  fi
-
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  [[ ! -d "$data_dir" ]] && mkdir -p -m 700 "$data_dir" >/dev/null 2>&1
   echo "Starting $BASENAME."
-#  $BINFILE -D -f $CFGFILE -p $PIDFILE >$LOGFILE 2>&1
-  $BINFILE -D -f $CFGFILE -p $PIDFILE 2> /dev/null
-  RETVAL=$?
   echo
+  $BINFILE -D -f $CFGFILE -p $PIDFILE >/dev/null 2>&1
+  RETVAL=$?
   return $RETVAL
 }
 
-stop() {
-  if [ -e $PIDFILE ]; then
-    echo "Shutting down $BASENAME."
-    pid=$(GetPID $BASENAME)
-    kill -USR1 "$pid"
-    RETVAL=$?
-    echo
-    [ $RETVAL -eq 0 ] && rm -f $PIDFILE
-    return $RETVAL
-  else
+stop () {
+  [[ ! -e $PIDFILE ]] && {
     echo "$BASENAME is not running."
-    return 0
-  fi
+    echo
+    RETVAL=0
+    return $RETVAL
+  }
+  echo "Shutting down $BASENAME."
+  echo
+  pid=$(GetPID $BASENAME)
+  kill -USR1 "$pid"
+  RETVAL=$?
+  [[ $RETVAL -eq 0 ]] && rm -f $PIDFILE >/dev/null 2>&1
+  return $RETVAL
 }
 
-restart() {
+restart () {
   quiet_check
-  if [ $? -ne 0 ]; then
+  [[ $? -ne 0 ]] && {
     echo "Errors found in configuration file, check it with '$0 check'."
-    return 1
-  fi
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
   stop
   start
 }
 
-reload() {
-  if [ ! -e $PIDFILE ]; then
+reload () {
+  [[ ! -e $PIDFILE ]] && {
     echo "$BASENAME is not running."
-    return 1
-  fi
-
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
   quiet_check
-  if [ $? -ne 0 ]; then
+  [[ $? -ne 0 ]] && {
     echo "Errors found in configuration file, check it with '$0 check'."
-    return 1
-  fi
-
-  $BINFILE -D -f $CFGFILE -p $PIDFILE -sf $(cat $PIDFILE) 2> /dev/null
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  $BINFILE -D -f $CFGFILE -p $PIDFILE -sf $(cat $PIDFILE) >/dev/null 2>&1
 }
 
-check() {
+check () {
   $BINFILE -c -q -V -f $CFGFILE
 }
 
-quiet_check() {
+quiet_check () {
   $BINFILE -c -q -f $CFGFILE
 }
 
-condrestart() {
-  if [ ! -e $PIDFILE ]; then
+condrestart () {
+  [[ ! -e $PIDFILE ]] && {
     echo "$BASENAME is not running."
-    return 1
-  fi
-
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
   quiet_check
-  if [ $? -ne 0 ]; then
+  [[ $? -ne 0 ]] && {
     echo "Errors found in configuration file, check it with '$0 check'."
-    return 1
-  fi
-
-  [ -e $PIDFILE ] && restart || :
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  [[ -e $PIDFILE ]] && restart || :
 }
 
 ##
diff --git a/Linux/privoxy b/Linux/privoxy
--- a/Linux/privoxy
+++ b/Linux/privoxy
@@ -4,7 +4,7 @@
 #
 # Purpose     :  A Privoxy Enhancing Proxy launch/terminate/... script
 #
-# Copyright   :  Written by and Copyright (C) 2023-03-17
+# Copyright   :  Written by and Copyright (C) 2023-04-26
 #                Miles Guo. komg@hotmail.com
 #
 #                This program is free software; you can redistribute it
@@ -39,73 +39,78 @@ EOF
   exit 1
 }
 
-[ $# -ne 1 ] && usage
+[[ $# -ne 1 ]] && usage
 
 . rc.common
 
 BASENAME=`basename $0`
+
 # check privoxy
 BINPATH=/usr/local/sbin
 BINFILE=$BINPATH/$BASENAME
-if [ ! -x $BINFILE ]; then
+[[ ! -x $BINFILE ]] && {
   echo "Sorry, you haven't installed $BASENAME yet."
   echo "Please refer to the readme.md for the solution."
+  echo
   exit 1
-fi
+}
 
 CFGFILE=$PWD/$BASENAME.cfg
-[ -f $CFGFILE ] || exit 1
+[[ -f $CFGFILE ]] || {
+  echo "Sorry, I can't find $CFGFILE, that is used to with $BASENAME."
+  echo
+  exit 1
+}
+
 data_dir=$PWD/run/$BASENAME
 PIDFILE=$data_dir/$BASENAME.pid
 
 RETVAL=0
 
-start() {
-  if [ -e $PIDFILE ]; then
+start () {
+  [[ -e $PIDFILE ]] && {
     echo "$BASENAME is already running."
-    return 0
-  fi
-
-  if [ ! -d "$data_dir" ]; then
-    echo "Creating directory $data_dir"
-    mkdir -p -m 700 "$data_dir"
-  fi
-
+    echo
+    RETVAL=0
+    return $RETVAL
+  }
+  [[ ! -d "$data_dir" ]] && mkdir -p -m 700 "$data_dir" >/dev/null 2>&1
   echo "Starting $BASENAME enhancing proxy."
-#  $BINFILE --no-daemon --pidfile $PIDFILE $CFGFILE >$LOGFILE 2>&1 &
-  $BINFILE --no-daemon --pidfile $PIDFILE $CFGFILE 2>/dev/null &
-  RETVAL=$?
   echo
+  $BINFILE --no-daemon --pidfile $PIDFILE $CFGFILE >/dev/null 2>&1 &
+  RETVAL=$?
   return $RETVAL
 }
 
-stop() {
-  if [ -e $PIDFILE ]; then
-    echo "Shutting down $BASENAME."
-    pid=$(GetPID $BASENAME)
-    kill -TERM "$pid"
-    RETVAL=$?
-    echo
-    [ $RETVAL -eq 0 ] && rm -f $PIDFILE
-    return $RETVAL
-  else
+stop () {
+  [[ ! -e $PIDFILE ]] && {
     echo "$BASENAME is not running."
-    return 0
-  fi
+    echo
+    RETVAL=0
+    return $RETVAL
+  }
+  echo "Shutting down $BASENAME."
+  echo
+  pid=$(GetPID $BASENAME)
+  kill -TERM "$pid"
+  RETVAL=$?
+  [[ $RETVAL -eq 0 ]] && rm -f $PIDFILE >/dev/null 2>&1
+  return $RETVAL
 }
 
-restart() {
-  if [ -e $PIDFILE ]; then
-    echo "Restarting $BASENAME enhancing proxy."
-    pid=$(GetPID $BASENAME)
-    kill -HUP "$pid"
-    RETVAL=$?
-    echo
-    return $RETVAL
-  else
+restart () {
+  [[ ! -e $PIDFILE ]] && {
     stop
     start
-  fi
+    RETVAL=$?
+    return $RETVAL
+  }
+  echo "Restarting $BASENAME enhancing proxy."
+  echo
+  pid=$(GetPID $BASENAME)
+  kill -HUP "$pid"
+  RETVAL=$?
+  return $RETVAL
 }
 
 ##
diff --git a/Linux/tor b/Linux/tor
--- a/Linux/tor
+++ b/Linux/tor
@@ -4,7 +4,7 @@
 #
 # Purpose     :  A Tor(onion routers) launch/terminate/... script
 #
-# Copyright   :  Written by and Copyright (C) 2023-03-17
+# Copyright   :  Written by and Copyright (C) 2023-04-26
 #                Miles Guo. komg@hotmail.com
 #
 #                This program is free software; you can redistribute it
@@ -106,32 +106,40 @@ EOF
   exit 1
 }
 
-[ $# -ne 1 ] && usage
+[[ $# -ne 1 ]] && usage
 
 BASENAME=`basename $0`
+
+TOR_SIGNAL="$1"
 
 # check nc
 NCPATH=/usr/bin
 NCBIN=$NCPATH/nc
-if [ ! -x $NCBIN ]; then
+[[ ! -x $NCBIN ]] && {
   echo "Sorry, I can't find nc, that is used to communicate with Tor process."
   echo "The control signals needs to be send via nc/netcat."
   echo "Please refer to the readme.md for the solution."
+  echo
   exit 1
-fi
+}
 
 # check tor
 TEBPATH=$PWD/tor-expert-bundle
 TORPATH=$TEBPATH/$BASENAME
 TORBIN=$TORPATH/$BASENAME
-if [ ! -x $TORBIN ]; then
+[[ ! -x $TORBIN ]] && {
   echo "Sorry, I can't find $BASENAME."
   echo "Please refer to the readme.md to download and install the Tor Expert Bundle first."
+  echo
   exit 1
-fi
+}
 
-TOR_TORRC=$PWD/torrc
-[ -f $TOR_TORRC ] || exit 1
+TOR_TORRC=$PWD/torrc.cfg
+[[ -f $TOR_TORRC ]] || {
+  echo "Sorry, I can't find torrc, that is used to with Tor process."
+  echo
+  exit 1
+}
 TOR_GEOIP=$TEBPATH/data/geoip
 TOR_GEOIP6=$TEBPATH/data/geoip6
 
@@ -145,160 +153,157 @@ RUNPATH=$PWD/run
 
 RETVAL=0
 
-start() {
+start () {
   PIDFILE=$RUNPATH/$BASENAME/$BASENAME.pid
   LOGFILE=$RUNPATH/$BASENAME/$BASENAME.log
-  if [ -e $PIDFILE ]; then
+  [[ -e $PIDFILE ]] && {
     echo "$BASENAME is already running."
+    echo
     RETVAL=0
-    echo
-  else
-    data_dir=$RUNPATH/$BASENAME
-    if [ ! -d "$data_dir" ]; then
-      echo "Creating directory $data_dir"
-      mkdir -p -m 700 "$data_dir"
-    fi
-    socks_port=$((TOR_BASE_SOCKS_PORT))
-    control_port=$((TOR_BASE_CTRL_PORT))
-    echo "Starting $BASENAME"
-    OLDPATH=$PWD
-    cd $TORPATH
-    $TORBIN --PidFile $PIDFILE -f $TOR_TORRC --DataDirectory $data_dir --GeoIPFile $TOR_GEOIP --GeoIPv6File $TOR_GEOIP6 --HashedControlPassword $TOR_HASHPASS --NewCircuitPeriod 60 --ControlPort $control_port --SocksPort "$TOR_HOST:$socks_port IPv6Traffic PreferIPv6 KeepAliveIsolateSOCKSAuth" >$LOGFILE 2>&1 &
-    RETVAL=$?
-    echo
-    cd $OLDPATH
-  fi
+    return $RETVAL
+  }
+  data_dir=$RUNPATH/$BASENAME
+  [[ ! -d "$data_dir" ]] && mkdir -p -m 700 "$data_dir" >/dev/null 2>&1
+  socks_port=$((TOR_BASE_SOCKS_PORT))
+  control_port=$((TOR_BASE_CTRL_PORT))
+  echo "Starting $BASENAME"
+  echo
+  OLDPATH=$PWD
+  cd $TORPATH
+  $TORBIN --PidFile $PIDFILE -f $TOR_TORRC --DataDirectory $data_dir --GeoIPFile $TOR_GEOIP --GeoIPv6File $TOR_GEOIP6 --HashedControlPassword $TOR_HASHPASS --NewCircuitPeriod 60 --ControlPort $control_port --SocksPort "$TOR_HOST:$socks_port IPv6Traffic PreferIPv6 KeepAliveIsolateSOCKSAuth" >$LOGFILE 2>&1 &
+  RETVAL=$?
+  cd $OLDPATH
   return $RETVAL
 }
 
-stop() {
+stop () {
   PIDFILE=$RUNPATH/$BASENAME/$BASENAME.pid
   LOGFILE=$RUNPATH/$BASENAME/$BASENAME.log
-  if [ -e $PIDFILE ]; then
-    echo "Shutting down $BASENAME"
-    control_port=$((TOR_BASE_CTRL_PORT))
-    $NCBIN $TOR_HOST $control_port << EOF
+  [[ ! -e $PIDFILE ]] && {
+    echo "$BASENAME is not running."
+    echo
+    RETVAL=0
+    return $RETVAL
+  }
+  echo "Shutting down $BASENAME"
+  echo
+  control_port=$((TOR_BASE_CTRL_PORT))
+  $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
 SIGNAL SHUTDOWN
 QUIT
 EOF
-    RETVAL=$?
-    echo
-    [ $RETVAL -eq 0 ] && rm -f $PIDFILE
-    [ $RETVAL -eq 0 ] && rm -f $LOGFILE
-  else
-    echo "$BASENAME is not running."
-    RETVAL=0
-    echo
-  fi
+  RETVAL=$?
+  [[ $RETVAL -eq 0 ]] && rm -f $PIDFILE >/dev/null 2>&1
+  [[ $RETVAL -eq 0 ]] && rm -f $LOGFILE >/dev/null 2>&1
   return $RETVAL
 }
 
-reload() {
+reload () {
   PIDFILE=$RUNPATH/$BASENAME/$BASENAME.pid
-  if [ -e $PIDFILE ]; then
-    echo "$BASENAME: reload config items."
-    control_port=$((TOR_BASE_CTRL_PORT))
-    $NCBIN $TOR_HOST $control_port << EOF
+  [[ ! -e $PIDFILE ]] && {
+    echo "$BASENAME is not running."
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  echo "$BASENAME: reload config items."
+  echo
+  control_port=$((TOR_BASE_CTRL_PORT))
+  $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
 SIGNAL RELOAD
 QUIT
 EOF
-    RETVAL=$?
-    echo
-  else
-    echo "$BASENAME is not running."
-    RETVAL=1
-    echo
-  fi
+  RETVAL=$?
   return $RETVAL
 }
 
-cleardnscache() {
+cleardnscache () {
   PIDFILE=$RUNPATH/$BASENAME/$BASENAME.pid
-  if [ -e $PIDFILE ]; then
-    echo "$BASENAME: Forget the client-side cached IPs for all hostnames."
-    control_port=$((TOR_BASE_CTRL_PORT))
-    $NCBIN $TOR_HOST $control_port << EOF
+  [[ ! -e $PIDFILE ]] && {
+    echo "$BASENAME is not running."
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  echo "$BASENAME: Forget the client-side cached IPs for all hostnames."
+  echo
+  control_port=$((TOR_BASE_CTRL_PORT))
+  $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
 SIGNAL CLEARDNSCACHE
 QUIT
 EOF
-    RETVAL=$?
-    echo
-  else
-    echo "$BASENAME is not running."
-    RETVAL=1
-    echo
-  fi
+  RETVAL=$?
   return $RETVAL
 }
 
-newnym() {
+newnym () {
   PIDFILE=$RUNPATH/$BASENAME/$BASENAME.pid
-  if [ -e $PIDFILE ]; then
-    echo "$BASENAME: Switch to clean circuits."
-    control_port=$((TOR_BASE_CTRL_PORT))
-    $NCBIN $TOR_HOST $control_port << EOF
+  [[ ! -e $PIDFILE ]] && {
+    echo "$BASENAME is not running."
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  echo "$BASENAME: Switch to clean circuits."
+  echo
+  control_port=$((TOR_BASE_CTRL_PORT))
+  $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
 SIGNAL NEWNYM
 QUIT
 EOF
-    RETVAL=$?
-    echo
-    sleep 10
-  else
-    echo "$BASENAME is not running."
-    RETVAL=1
-    echo
-  fi
+  RETVAL=$?
+  sleep 10
   return $RETVAL
 }
 
-dormant() {
+dormant () {
   PIDFILE=$RUNPATH/$BASENAME/$BASENAME.pid
-  if [ -e $PIDFILE ]; then
-    echo "$BASENAME: To become dormant."
-    control_port=$((TOR_BASE_CTRL_PORT))
-    $NCBIN $TOR_HOST $control_port << EOF
+  [[ ! -e $PIDFILE ]] && {
+    echo "$BASENAME is not running."
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  echo "$BASENAME: To become dormant."
+  echo
+  control_port=$((TOR_BASE_CTRL_PORT))
+  $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
 SIGNAL DORMANT
 QUIT
 EOF
-    RETVAL=$?
-    echo
-  else
-    echo "$BASENAME is not running."
-    RETVAL=1
-    echo
-  fi
+  RETVAL=$?
   return $RETVAL
 }
 
-active() {
+active () {
   PIDFILE=$RUNPATH/$BASENAME/$BASENAME.pid
-  if [ -e $PIDFILE ]; then
-    echo "$BASENAME: To stop being dormant."
-    control_port=$((TOR_BASE_CTRL_PORT))
-    $NCBIN $TOR_HOST $control_port << EOF
+  [[ ! -e $PIDFILE ]] && {
+    echo "$BASENAME is not running."
+    echo
+    RETVAL=1
+    return $RETVAL
+  }
+  echo "$BASENAME: To stop being dormant."
+  echo
+  control_port=$((TOR_BASE_CTRL_PORT))
+  $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
 SIGNAL ACTIVE
 QUIT
 EOF
-    RETVAL=$?
-    echo
-  else
-    echo "$BASENAME is not running."
-    RETVAL=1
-    echo
-  fi
+  RETVAL=$?
   return $RETVAL
 }
 
 ##
 # Generic action handler
 ##
-case "$1" in 
+case "$TOR_SIGNAL" in 
   start         ) start;;
   reload        ) reload;;
   stop          ) stop;;
diff --git a/macOS/mtor b/macOS/mtor
--- a/macOS/mtor
+++ b/macOS/mtor
@@ -4,7 +4,7 @@
 #
 # Purpose     :  A Multiple Tor(onion routers) launch/terminate/... script
 #
-# Copyright   :  Written by and Copyright (C) 2023-03-15
+# Copyright   :  Written by and Copyright (C) 2023-04-26
 #                Miles Guo. komg@hotmail.com
 #
 #                This program is free software; you can redistribute it
@@ -107,33 +107,42 @@ EOF
   exit 1
 }
 
-[ $# -ne 2 ] && usage
+[[ $# -ne 2 ]] && usage
+
+expr $1 + 0 >/dev/null 2>&1
+[[ $? -ne 0 ]] && usage
 
 TOR_INSTANCES="$1"
-#TOR_SIGNAL="$2"
+TOR_SIGNAL="$2"
 
 # check nc
 NCPATH=/usr/bin
 NCBIN=$NCPATH/nc
-if [ ! -x $NCBIN ]; then
+[[ ! -x $NCBIN ]] && {
   echo "Sorry, I can't find nc, that is used to communicate with Tor process."
   echo "The control signals needs to be send via nc/netcat."
   echo "Please refer to the readme.md for the solution."
+  echo
   exit 1
-fi
+}
 
 # check tor
 TEBPATH=$PWD/tor-expert-bundle
 TORPATH=$TEBPATH/tor
 TORBIN=$TORPATH/tor
-if [ ! -x $TORBIN ]; then
-  echo "Sorry, I can't find tor."
+[[ ! -x $TORBIN ]] && {
+  echo "Sorry, I can't find $TORBIN."
   echo "Please refer to the readme.md to download and install the Tor Expert Bundle first."
+  echo
   exit 1
-fi
+}
 
-TOR_TORRC=$PWD/torrc
-[ -f $TOR_TORRC ] || exit 1
+TOR_TORRC=$PWD/torrc.cfg
+[[ -f $TOR_TORRC ]] || {
+  echo "Sorry, I can't find torrc, that is used to with Tor process."
+  echo
+  exit 1
+}
 TOR_GEOIP=$TEBPATH/data/geoip
 TOR_GEOIP6=$TEBPATH/data/geoip6
 
@@ -148,46 +157,48 @@ RUNPATH=$PWD/run
 RETVAL=0
 mRETVAL=0
 
-start() {
+start () {
   num=`expr $TOR_INSTANCES - 0`
   for i in $(seq 1 $num)
   do
     PIDFILE=$RUNPATH/tor$i/tor$i.pid
     LOGFILE=$RUNPATH/tor$i/tor$i.log
-    if [ -e $PIDFILE ]; then
+    [[ -e $PIDFILE ]] && {
       echo "tor$i is already running."
-      mRETVAL=0
       echo
-    else
+      mRETVAL=0
+    } || {
       data_dir=$RUNPATH/tor$i
-      if [ ! -d "$data_dir" ]; then
-        echo "Creating directory $data_dir"
-        mkdir -p -m 700 "$data_dir"
-      fi
+      [[ ! -d "$data_dir" ]] && mkdir -p -m 700 "$data_dir" >/dev/null 2>&1
       socks_port=$((TOR_BASE_SOCKS_PORT+$i))
       control_port=$((TOR_BASE_CTRL_PORT+$i))
       echo "Starting tor$i"
+      echo
       OLDPATH=$PWD
       cd $TORPATH
       $TORBIN --PidFile $PIDFILE -f $TOR_TORRC --DataDirectory $data_dir --GeoIPFile $TOR_GEOIP --GeoIPv6File $TOR_GEOIP6 --HashedControlPassword $TOR_HASHPASS --NewCircuitPeriod 60 --ControlPort $control_port --SocksPort "$TOR_HOST:$socks_port IPv6Traffic PreferIPv6 KeepAliveIsolateSOCKSAuth" >$LOGFILE 2>&1 &
       mRETVAL=$?
-      echo
       cd $OLDPATH
-    fi
+    }
     RETVAL=`expr $RETVAL + $mRETVAL`
     i=`expr $i + 1`
   done
   return $RETVAL
 }
 
-stop() {
+stop () {
   num=`expr $TOR_INSTANCES - 0`
   for i in $(seq 1 $num)
   do
     PIDFILE=$RUNPATH/tor$i/tor$i.pid
     LOGFILE=$RUNPATH/tor$i/tor$i.log
-    if [ -e $PIDFILE ]; then
+    [[ ! -e $PIDFILE ]] && {
+      echo "tor$i is not running."
+      echo
+      mRETVAL=0
+    } || {
       echo "Shutting down tor$i"
+      echo
       control_port=$((TOR_BASE_CTRL_PORT+$i))
       $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
@@ -195,27 +206,27 @@ SIGNAL SHUTDOWN
 QUIT
 EOF
       mRETVAL=$?
-      echo
-      [ $mRETVAL -eq 0 ] && rm -f $PIDFILE
-      [ $mRETVAL -eq 0 ] && rm -f $LOGFILE
-    else
-      echo "tor$i is not running."
-      mRETVAL=0
-      echo
-    fi
+      [[ $mRETVAL -eq 0 ]] && rm -f $PIDFILE >/dev/null 2>&1
+      [[ $mRETVAL -eq 0 ]] && rm -f $LOGFILE >/dev/null 2>&1
+    }
     RETVAL=`expr $RETVAL + $mRETVAL`
     i=`expr $i + 1`
   done
   return $RETVAL
 }
 
-reload() {
+reload () {
   num=`expr $TOR_INSTANCES - 0`
   for i in $(seq 1 $num)
   do
     PIDFILE=$RUNPATH/tor$i/tor$i.pid
-    if [ -e $PIDFILE ]; then
+    [[ ! -e $PIDFILE ]] && {
+      echo "tor$i is not running."
+      echo
+      mRETVAL=1
+    } || {
       echo "tor$i: reload config items."
+      echo
       control_port=$((TOR_BASE_CTRL_PORT+$i))
       $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
@@ -223,25 +234,25 @@ SIGNAL RELOAD
 QUIT
 EOF
       mRETVAL=$?
-      echo
-    else
-      echo "tor$i is not running."
-      mRETVAL=1
-      echo
-    fi
+    }
     RETVAL=`expr $RETVAL + $mRETVAL`
     i=`expr $i + 1`
   done
   return $RETVAL
 }
 
-cleardnscache() {
+cleardnscache () {
   num=`expr $TOR_INSTANCES - 0`
   for i in $(seq 1 $num)
   do
     PIDFILE=$RUNPATH/tor$i/tor$i.pid
-    if [ -e $PIDFILE ]; then
+    [[ ! -e $PIDFILE ]] && {
+      echo "tor$i is not running."
+      echo
+      mRETVAL=1
+    } || {
       echo "tor$i: Forget the client-side cached IPs for all hostnames."
+      echo
       control_port=$((TOR_BASE_CTRL_PORT+$i))
       $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
@@ -249,25 +260,25 @@ SIGNAL CLEARDNSCACHE
 QUIT
 EOF
       mRETVAL=$?
-      echo
-    else
-      echo "tor$i is not running."
-      mRETVAL=1
-      echo
-    fi
+    }
     RETVAL=`expr $RETVAL + $mRETVAL`
     i=`expr $i + 1`
   done
   return $RETVAL
 }
 
-newnym() {
+newnym () {
   num=`expr $TOR_INSTANCES - 0`
   for i in $(seq 1 $num)
   do
     PIDFILE=$RUNPATH/tor$i/tor$i.pid
-    if [ -e $PIDFILE ]; then
+    [[ ! -e $PIDFILE ]] && {
+      echo "tor$i is not running."
+      echo
+      mRETVAL=1
+    } || {
       echo "tor$i: Switch to clean circuits."
+      echo
       control_port=$((TOR_BASE_CTRL_PORT+$i))
       $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
@@ -275,26 +286,26 @@ SIGNAL NEWNYM
 QUIT
 EOF
       mRETVAL=$?
-      echo
       sleep 10
-    else
-      echo "tor$i is not running."
-      mRETVAL=1
-      echo
-    fi
+    }
     RETVAL=`expr $RETVAL + $mRETVAL`
     i=`expr $i + 1`
   done
   return $RETVAL
 }
 
-dormant() {
+dormant () {
   num=`expr $TOR_INSTANCES - 0`
   for i in $(seq 1 $num)
   do
     PIDFILE=$RUNPATH/tor$i/tor$i.pid
-    if [ -e $PIDFILE ]; then
+    [[ ! -e $PIDFILE ]] && {
+      echo "tor$i is not running."
+      echo
+      mRETVAL=1
+    } || {
       echo "tor$i: To become dormant."
+      echo
       control_port=$((TOR_BASE_CTRL_PORT+$i))
       $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
@@ -302,25 +313,25 @@ SIGNAL DORMANT
 QUIT
 EOF
       mRETVAL=$?
-      echo
-    else
-      echo "tor$i is not running."
-      mRETVAL=1
-      echo
-    fi
+    }
     RETVAL=`expr $RETVAL + $mRETVAL`
     i=`expr $i + 1`
   done
   return $RETVAL
 }
 
-active() {
+active () {
   num=`expr $TOR_INSTANCES - 0`
   for i in $(seq 1 $num)
   do
     PIDFILE=$RUNPATH/tor$i/tor$i.pid
-    if [ -e $PIDFILE ]; then
+    [[ ! -e $PIDFILE ]] && {
+      echo "tor$i is not running."
+      echo
+      mRETVAL=1
+    } || {
       echo "tor$i: To stop being dormant."
+      echo
       control_port=$((TOR_BASE_CTRL_PORT+$1))
       $NCBIN $TOR_HOST $control_port << EOF
 AUTHENTICATE "$TOR_PASS"
@@ -328,12 +339,7 @@ SIGNAL ACTIVE
 QUIT
 EOF
       mRETVAL=$?
-      echo
-    else
-      echo "tor$i is not running."
-      mRETVAL=1
-      echo
-    fi
+    }
     RETVAL=`expr $RETVAL + $mRETVAL`
     i=`expr $i + 1`
   done
@@ -343,7 +349,7 @@ EOF
 ##
 # Generic action handler
 ##
-case "$2" in 
+case "$TOR_SIGNAL" in 
   start         ) start;;
   reload        ) reload;;
   stop          ) stop;;
